POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "nametest@gmail.com", 
    "password": "Testons1"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "nametest@gmail.com", 
    "password": "Testons1"
}
###
GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDUwYjUyZmVjOGNlNjBmODQxY2ZjYzUiLCJpYXQiOjE2MTU5MDIwMTUsImV4cCI6MTYxNTkwOTIxNX0.jL4yQontFFDiieJfvvKCVPSZSS6rbAiOiu9XMUX2yTc
###
GET http://localhost:3000/api/sauces/6050b084ec8ce60f841cfcc4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDUwYjUyZmVjOGNlNjBmODQxY2ZjYzUiLCJpYXQiOjE2MTU5MDIwMTUsImV4cCI6MTYxNTkwOTIxNX0.jL4yQontFFDiieJfvvKCVPSZSS6rbAiOiu9XMUX2yTc
###
PUT http://localhost:3000/api/sauces/6050b084ec8ce60f841cfcc4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDUwYjUyZmVjOGNlNjBmODQxY2ZjYzUiLCJpYXQiOjE2MTU5MDIwMTUsImV4cCI6MTYxNTkwOTIxNX0.jL4yQontFFDiieJfvvKCVPSZSS6rbAiOiu9XMUX2yTc
Content-Type: application/json

{
    "heat": 5
}